# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userlogin.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class MyLogin(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(1030, 497)
        self.centralwidget = QtWidgets.QWidget(login)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 30, 501, 131))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.rb1 = QtWidgets.QRadioButton(self.groupBox)
        self.rb1.setGeometry(QtCore.QRect(20, 50, 261, 51))
        self.rb1.setObjectName("rb1")
        self.rb2 = QtWidgets.QRadioButton(self.groupBox)
        self.rb2.setGeometry(QtCore.QRect(310, 50, 151, 51))
        self.rb2.setObjectName("rb2")
        self.gb1 = QtWidgets.QGroupBox(self.centralwidget)
        self.gb1.setEnabled(True)
        self.gb1.setGeometry(QtCore.QRect(20, 190, 471, 251))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gb1.setFont(font)
        self.gb1.setObjectName("gb1")
        self.l1 = QtWidgets.QLabel(self.gb1)
        self.l1.setGeometry(QtCore.QRect(30, 30, 161, 41))
        self.l1.setObjectName("l1")
        self.l2 = QtWidgets.QLabel(self.gb1)
        self.l2.setGeometry(QtCore.QRect(30, 90, 161, 41))
        self.l2.setObjectName("l2")
        self.t1 = QtWidgets.QLineEdit(self.gb1)
        self.t1.setGeometry(QtCore.QRect(180, 40, 241, 31))
        self.t1.setObjectName("t1")
        self.t2 = QtWidgets.QLineEdit(self.gb1)
        self.t2.setGeometry(QtCore.QRect(180, 100, 241, 31))
        self.t2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.t2.setObjectName("t2")
        self.button1 = QtWidgets.QPushButton(self.gb1)
        self.button1.setGeometry(QtCore.QRect(200, 150, 111, 41))
        self.button1.setObjectName("button1")
        self.button_1 = QtWidgets.QPushButton(self.gb1)
        self.button_1.setGeometry(QtCore.QRect(310, 150, 91, 41))
        self.button_1.setObjectName("button_1")
        self.label1 = QtWidgets.QLabel(self.gb1)
        self.label1.setGeometry(QtCore.QRect(10, 200, 441, 41))
        self.label1.setText("")
        self.label1.setObjectName("label1")
        self.gb2 = QtWidgets.QGroupBox(self.centralwidget)
        self.gb2.setEnabled(True)
        self.gb2.setGeometry(QtCore.QRect(520, 190, 471, 251))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gb2.setFont(font)
        self.gb2.setObjectName("gb2")
        self.l3 = QtWidgets.QLabel(self.gb2)
        self.l3.setGeometry(QtCore.QRect(30, 30, 161, 41))
        self.l3.setObjectName("l3")
        self.l4 = QtWidgets.QLabel(self.gb2)
        self.l4.setGeometry(QtCore.QRect(30, 90, 161, 31))
        self.l4.setObjectName("l4")
        self.t4 = QtWidgets.QLineEdit(self.gb2)
        self.t4.setGeometry(QtCore.QRect(180, 90, 241, 31))
        self.t4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.t4.setObjectName("t4")
        self.t3 = QtWidgets.QLineEdit(self.gb2)
        self.t3.setGeometry(QtCore.QRect(180, 40, 241, 31))
        self.t3.setObjectName("t3")
        self.button2_2 = QtWidgets.QPushButton(self.gb2)
        self.button2_2.setGeometry(QtCore.QRect(260, 150, 91, 41))
        self.button2_2.setObjectName("button2_2")
        self.button2 = QtWidgets.QPushButton(self.gb2)
        self.button2.setGeometry(QtCore.QRect(150, 150, 111, 41))
        self.button2.setObjectName("button2")
        self.label2 = QtWidgets.QLabel(self.gb2)
        self.label2.setGeometry(QtCore.QRect(10, 200, 441, 41))
        self.label2.setText("")
        self.label2.setObjectName("label2")
        #login.setCentralWidget(self.centralwidget)

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "MainWindow"))
        self.groupBox.setTitle(_translate("login", "Choose Your Option"))
        self.rb1.setText(_translate("login", "Register Yourself"))
        self.rb2.setText(_translate("login", "Login"))
        self.gb1.setTitle(_translate("login", "Register Yourself"))
        self.l1.setText(_translate("login", "Email"))
        self.l2.setText(_translate("login", "Password"))
        self.button1.setText(_translate("login", "Register"))
        self.button_1.setText(_translate("login", "Clear"))
        self.gb2.setTitle(_translate("login", "Login"))
        self.l3.setText(_translate("login", "Email"))
        self.l4.setText(_translate("login", "Password"))
        self.button2_2.setText(_translate("login", "Clear"))
        self.button2.setText(_translate("login", "SignIn"))
